#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Java CI with Maven

on:
  push:
    branches:
      - 20.0.2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          
      
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/build.sh') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: |
          cp ./maven-settings.xml ~/.m2/settings.xml
          chmod +x ./build.sh && ./build.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ATLAN_IT_S3_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ATLAN_IT_S3_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Copy build to S3 bucket
        run: aws s3 cp ./quarkus/dist/target/keycloak-20.0.2.tar.gz s3://atlan/artifact/keycloak-20.0.2.tar.gz --region $AWS_REGION --acl public-read
        env:
          AWS_REGION: "ap-south-1"
          AWS_S3_BUCKET: "atlan"
      
